import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Inter, Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfairDisplay.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-screen w-full flex flex-col">
        <div className="h-16 w-full z-30 absolute top-0 left-0">
          <Header />
        </div>

        <main className="flex-1">{children}</main>

        <div className="w-full z-30">
          <Footer />
        </div>
      </body>
    </html>
  );
}
